### ISSUE TITLE
Flow: registration

### ISSUE THREAD

**Issue by JustBeYou** [LittleWhoDev/HelpingAngel-Web#14]
Be sure that the following actions can be performed. Add e2e testing.
- [ ] Open the app and view the welcome screen #10 
- [ ] Select use case and proceed to login #1 
- [ ] Click the registration button, fill the form/use SSO (facebook, gmail) #1 
- [ ] Confirmation (if needed) 
- [ ] Login with your new account #1
