### ISSUE TITLE
Flow: view nearby posts on the map

### ISSUE THREAD

**Issue by JustBeYou** [LittleWhoDev/HelpingAngel-Web#15]
- [ ] Select the "donor" option and be able to log in or proceed anonymously
- [ ] Select the map view or view it by default if not logged in #4 #12 
- [x] Use map filters (distance, category) #6 
- [x] View post details #8
