### ISSUE TITLE
Flow: submit a post

### ISSUE THREAD

**Issue by JustBeYou** [LittleWhoDev/HelpingAngel-Web#16]
- [ ] Login and select the "add post" button in the navigation #7 
- [ ] Fill post form #9 
- [ ] View newly created post #8
